# Generated by Django 5.1.6 on 2025-05-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_rename_available_slots_tourpackage_available_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='currency',
            field=models.CharField(choices=[('USD', '($)'), ('INR', '(₹)'), ('EUR', '(€)'), ('GBP', '(£)')], default='INR', max_length=3),
        ),
    ]
