# Generated by Django 5.1.6 on 2025-05-24 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tourpackage_is_approved_alter_tourpackage_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='available_spots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendors_tourpackages', to=settings.AUTH_USER_MODEL),
        ),
    ]
