# Generated by Django 5.1.6 on 2025-05-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
