# Generated by Django 5.1.6 on 2025-05-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_tourpackage_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourPackage',
        ),
    ]
